"""Deterministic, offline target drawings for the icon-first phase."""

from __future__ import annotations

from .base import PixelTarget, parse_grid


_PATTERNS: dict[str, tuple[str, ...]] = {
    "heart": (
        ".##..##",
        "#######",
        "#######",
        "..####.",
        "..###..",
        "...##..",
    ),
    "arrow": (
        "....###...",
        "#####.####",
        ".........#",
        ".........#",
        ".......###",
        "#####.##..",
        "....###...",
    ),
    "lightning": (
        "......#",
        "......#",
        "....###",
        "....#..",
        "...##..",
        "..##...",
        "..#....",
        "..#####",
        "......#",
        "...####",
        "...#...",
        ".###...",
        "##.....",
    ),
    # Recognition-first demo glyphs.  Unlike the looser visual targets above,
    # each mask has exactly 27 cells and has an exact threading under the
    # shipped roll.  The deliberately chunky strokes survive the cube gaps in
    # a clean silhouette render.
    "plus": (
        "...##...",
        ".######.",
        ".#######",
        "########",
        "...##...",
        "...##...",
    ),
    "h": (
        "##....",
        "###.##",
        "###..#",
        "######",
        "##..##",
        "##..##",
        "##....",
    ),
    "t": (
        "##########",
        "##########",
        "......#...",
        "......#...",
        "......#...",
        "......#...",
        "......#...",
        "......#...",
        "......#...",
    ),
    "n": (
        "###..#",
        "#.##.#",
        "#..#.#",
        "#..#.#",
        "#..#.#",
        "#..#.#",
        "#..#.#",
        "#..###",
    ),
    "house": (
        "...#...",
        "..#.#..",
        ".#...#.",
        "#######",
        "#.....#",
        "#..#..#",
        "#######",
    ),
    "fish": (
        "......#.",
        "..###..#",
        ".#...###",
        "#.....##",
        ".#...###",
        "..###..#",
        "......#.",
    ),
    "star": (
        "....#....",
        "....#....",
        "...#.#...",
        "###...###",
        ".#.....#.",
        "..#...#..",
        "..#.#.#..",
        ".#.....#.",
    ),
    "music-note": (
        "...####",
        "...#..#",
        "...#...",
        "...#...",
        "...#...",
        ".###...",
        "#..#...",
        ".##....",
    ),
    "key": (
        ".###....",
        "#...#...",
        "#...#...",
        ".###....",
        "...#....",
        "....#.#.",
        ".....###",
    ),
    "question-mark": (
        ".####.",
        "#....#",
        "....#.",
        "...#..",
        "..#...",
        "......",
        "..#...",
    ),
    "smiley": (
        ".#####.",
        "#.....#",
        "#.#.#.#",
        "#.....#",
        "#.#.#.#",
        "#..#..#",
        ".#####.",
    ),
    # Exploration winners (docs/EXPLORATION-20260919.md): exact 27-cell
    # shipped-roll threadings with a complete loose-passing fold, judged
    # recognizable in review.  Not part of DEMO_NAMES.
    "c": (  # c-v5
        "#######",
        "#######",
        "##.....",
        "##.....",
        "##.....",
        "##.....",
        "#####..",
    ),
    "j": (  # j-v3
        ".....##",
        "......#",
        "......#",
        "......#",
        "......#",
        "......#",
        "##....#",
        "##....#",
        "#######",
        "#######",
    ),
    "m": (  # m-v10
        "###.###",
        "#.#.#.#",
        "#.#.#.#",
        "#.#.#.#",
        "#.#.#.#",
        "#.###.#",
    ),
    "square-wave": (  # wave-v7
        "#....######....",
        "#....#....#....",
        "#....#....#....",
        "#....#....#....",
        "######....#####",
    ),
    "w": (  # w-v10
        "#.###.#",
        "#.#.#.#",
        "#.#.#.#",
        "#.#.#.#",
        "#.#.#.#",
        "###.###",
    ),
    "mug": (  # mug-v2
        "#####..",
        "#...#..",
        "#...#..",
        "#...###",
        "#...#.#",
        "#...###",
        "#...#..",
        "#####..",
    ),
    "2": (  # d2-v2
        "#####",
        "####.",
        "...##",
        "#####",
        "#....",
        "#####",
        "#####",
    ),
    "5": (  # d5-v2
        "#####",
        ".####",
        "##...",
        "#####",
        "....#",
        "#####",
        "#####",
    ),
    "k": (  # k-v9
        "##..##",
        "##.###",
        "##.#..",
        "####..",
        "###...",
        "#####.",
        "##..#.",
    ),
    "s": (  # s-v6
        "######",
        "#.....",
        "#.....",
        "######",
        ".....#",
        "######",
        "######",
    ),
    "checkmark": (  # checkmark-v1
        "...........###",
        "..........##..",
        "..........#...",
        "........###...",
        "........#.....",
        "#.....###.....",
        "#....##.......",
        "###..#........",
        "..#.##........",
        "..###.........",
    ),
    "staircase": (  # staircase-v2
        "#........",
        "#........",
        "#........",
        "#........",
        "###......",
        "..#......",
        "..#......",
        "..#......",
        "..###....",
        "....#....",
        "....#....",
        "....#....",
        "....###..",
        "......#..",
        "......#..",
        "......#..",
        "......###",
        "........#",
        "........#",
    ),
    "i": (  # i-v8
        "######.",
        "####...",
        "...#...",
        "...#...",
        "...#...",
        "...#...",
        "...#...",
        "...#...",
        "...#...",
        "...####",
        ".######",
    ),
    "3": (  # d3-v5
        "######",
        ".....#",
        "...###",
        "...###",
        ".....#",
        ".....#",
        "######",
        "######",
    ),
    "v": (  # v-v3
        "##.....##",
        "##.....##",
        ".##....##",
        "..#...###",
        "..#...#..",
        "..#..##..",
        "..##.#...",
        "...###...",
    ),
    "dumbbell": (  # dumbbell-v5
        "##.......##",
        "##.......##",
        "###########",
        "###.......#",
        "###.......#",
    ),
    "4": (  # d4-v5
        "#...##",
        "#...##",
        "#...##",
        "######",
        "...###",
        "...###",
        "...###",
        "...###",
    ),
    "8": (  # d8-v4
        "#####",
        "#...#",
        "#...#",
        "#####",
        "#####",
        "#...#",
        "#...#",
        "####.",
    ),
    "l": (  # l-v3
        "###...",
        "###...",
        "###...",
        "###...",
        "###...",
        "######",
        "######",
    ),
    "1": (  # d1-v2
        "..##.",
        "####.",
        "####.",
        "..##.",
        "..##.",
        "..##.",
        "..##.",
        "#####",
        ".####",
    ),
    "bell": (  # bell-v4
        "..##..",
        ".####.",
        ".#..#.",
        ".####.",
        "######",
        "######",
        ".###..",
    ),
    "7": (  # d7-v4
        "######",
        "######",
        "....##",
        "....##",
        "....##",
        "...###",
        "..##..",
        "..##..",
        "..##..",
    ),
    "0": (  # d0-v8
        ".#####",
        "######",
        "#....#",
        "#....#",
        "#....#",
        "#....#",
        "#....#",
        "######",
    ),
    "u": (  # u-v4
        "##....##",
        "##....##",
        "##....##",
        "##....##",
        "##....##",
        ".#######",
    ),
    "anchor": (  # anchor-v4
        "..###...",
        "..#.#...",
        "..###...",
        "...##...",
        "...##...",
        "...##..#",
        "#..##..#",
        "########",
    ),
    "e": (  # e-v3
        "######",
        "#.....",
        "#.....",
        "######",
        "######",
        "#.....",
        "######",
    ),
    "square": (  # square-v1
        "########",
        "#......#",
        "#......#",
        "#......#",
        "#......#",
        "#......#",
        "#......#",
        "#####.##",
    ),
    "spiral": (  # spiral-v1
        "########",
        ".......#",
        ".......#",
        ".###...#",
        ".#.....#",
        ".#.....#",
        ".#.....#",
        ".#######",
    ),
    "y": (  # y-v2
        "##.....##",
        "####..###",
        "...#..#..",
        "...####..",
        "...##....",
        "...##....",
        "...##....",
        "...##....",
        "...##....",
    ),
    "6": (  # d6-v7
        ".#####",
        "##....",
        "##....",
        "##....",
        "######",
        "#....#",
        "#....#",
        "######",
    ),
    "9": (  # d9-v6
        "######",
        "#....#",
        "#....#",
        "######",
        "....##",
        "....##",
        "....##",
        "#####.",
    ),
    "flag": (  # flag-v2
        "#######",
        "#######",
        "#######",
        "#......",
        "#......",
        "#......",
        "#......",
        "#......",
        "#......",
    ),
    "f": (  # f-v3
        "######",
        "##...#",
        "##....",
        "####..",
        "####..",
        "##....",
        "##....",
        "##....",
        "##....",
    ),
    "ring": (  # ring-v1
        ".#####.",
        "##...##",
        "##....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "##...##",
        ".#####.",
    ),
    "boat": (  # boat-v6
        "..##.....",
        "..##.....",
        "####.....",
        "...#.....",
        "#########",
        "#########",
    ),
    "umbrella": (  # umbrella-v7
        "...##..",
        "#######",
        "#######",
        "....#..",
        "....#..",
        "..#.#..",
        "..#.#..",
        "..#.#..",
        "..###..",
    ),
    "a": (  # a-v3
        "..##..",
        ".###..",
        ".#.#..",
        "##.##.",
        "#####.",
        "##..#.",
        "##..##",
        "##..##",
    ),
}

_ALIASES = {
    "bolt": "lightning",
    "lightning-bolt": "lightning",
    "cross": "plus",
    "+": "plus",
    "letter-h": "h",
    "letter-t": "t",
    "letter-n": "n",
    "note": "music-note",
    "music": "music-note",
    "question": "question-mark",
    "?": "question-mark",
    "smile": "smiley",
    "letter-c": "c",
    "letter-j": "j",
    "letter-m": "m",
    "wave": "square-wave",
    "signal": "square-wave",
    "letter-w": "w",
    "cup": "mug",
    "two": "2",
    "digit-2": "2",
    "five": "5",
    "digit-5": "5",
    "letter-k": "k",
    "letter-s": "s",
    "check": "checkmark",
    "tick": "checkmark",
    "stairs": "staircase",
    "letter-i": "i",
    "three": "3",
    "digit-3": "3",
    "letter-v": "v",
    "barbell": "dumbbell",
    "four": "4",
    "digit-4": "4",
    "eight": "8",
    "digit-8": "8",
    "letter-l": "l",
    "one": "1",
    "digit-1": "1",
    "seven": "7",
    "digit-7": "7",
    "zero": "0",
    "digit-0": "0",
    "letter-u": "u",
    "letter-e": "e",
    "box": "square",
    "letter-y": "y",
    "six": "6",
    "digit-6": "6",
    "nine": "9",
    "digit-9": "9",
    "letter-f": "f",
    "o": "ring",
    "circle": "ring",
    "ship": "boat",
    "letter-a": "a",
}

ICON_NAMES = tuple(_PATTERNS)
DEMO_NAMES = ("heart", "arrow", "lightning", "plus", "h", "t", "n")
REJECTED_NAMES = ("house", "fish", "star", "music-note", "key", "question-mark", "smiley")
# Registered by the 2026-09-19 exploration; every entry is an exact 27-cell
# shipped-roll target with a complete loose-passing plan (see docs/EXPLORATION-20260919.md).
EXPLORED_NAMES = tuple(name for name in ICON_NAMES if name not in DEMO_NAMES + REJECTED_NAMES)


def get_icon(name: str) -> PixelTarget:
    normalized = name.strip().lower().replace("_", "-").replace(" ", "-")
    normalized = _ALIASES.get(normalized, normalized)
    try:
        rows = _PATTERNS[normalized]
    except KeyError as error:
        raise KeyError(f"unknown icon {name!r}; choose from {', '.join(ICON_NAMES)}") from error
    source = (
        "demo-family-certified"
        if normalized in {"arrow", "plus"}
        else "demo-curated-certified"
        if normalized == "lightning"
        else "parametric"
    )
    return PixelTarget(
        grid=parse_grid(rows),
        concept=normalized,
        caption=f"A flat pixel drawing of {normalized.replace('-', ' ')}",
        source=source,
    )


def icons() -> list[PixelTarget]:
    return [get_icon(name) for name in ICON_NAMES]


# One-deep 3-D shells found by the 2026-09-19 volumetric exploration
# (docs/METHOD.md, "The 3-D variant").  Values are layered masks — z-slices,
# top layer first, ``---`` between slices — parsed by ``cubot.shapes.parse_layers``.
# They are exact 27-cell shipped-roll targets with a complete passing plan under
# ``loose`` (tier 1) or ``platform`` (tier 2); the tier is recorded per entry.
_LAYERED_PATTERNS: dict[str, tuple[str, ...]] = {}
LAYERED_TIERS: dict[str, int] = {}
LAYERED_NAMES = tuple(_LAYERED_PATTERNS)


def get_layered_cells(name: str) -> tuple[tuple[int, int, int], ...]:
    """Cells of a registered one-deep 3-D shell (see ``LAYERED_NAMES``)."""

    from ..shapes import parse_layers

    normalized = name.strip().lower().replace("_", "-").replace(" ", "-")
    try:
        rows = _LAYERED_PATTERNS[normalized]
    except KeyError as error:
        raise KeyError(f"unknown shell {name!r}; choose from {', '.join(LAYERED_NAMES)}") from error
    return parse_layers(list(rows))
